### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by sklorpion** [jakubthedeveloper/PythonInternetRadio#1]
pi@raspberrypi:~ $ git clone git@github.com:jakubthedeveloper/PythonInternetRadio.git radio
Cloning into 'radio'...
git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
pi@raspberrypi:~ $

**Comment by jakubthedeveloper** [comment]
Readme updated, correct command is:

```
git clone https://github.com/jakubthedeveloper/PythonInternetRadio.git radio
```

**Comment by sklorpion** [comment]
Dziękuję. 
Nie myślałeś zrobić Bluetooth ale jako odbiornik? 
Ja mam raspberry do HiFi podpięte i tam wsadzone raspotify i Twoje dzieło. Jakby się dało wysyłać dźwięk z tel do raspberry to jeszcze lepiej. Pozdrawiam 

⁣Wysłano z BlueMail ​

W dniu 2 paź 2020, 07:59, o 07:59, użytkownik JakubTheDeveloper <notifications@github.com> napisał:

**Comment by jakubthedeveloper** [comment]
Masz na myśli to że raspberry miałby działać jak np. słuchawki czy głośnik Bluetooth?

**Comment by sklorpion** [comment]
Tak

⁣Wysłano z BlueMail ​

W dniu 3 paź 2020, 00:44, o 00:44, użytkownik JakubTheDeveloper <notifications@github.com> napisał:
